In [27]:
#기계학습 (머신러닝) 활용

ds3_stockQuant.ipynb

In [2]:
_ohlcv = {
        'Open': [100, 101, 102, 103, 104, 105, 104, 103, 102, 101, 100, 99, 98, 97, 96, 97, 98],
    'High': [101, 102, 103, 104, 105, 106, 105, 104, 103, 102, 101, 100, 99, 98, 97, 98, 99],
    'Low': [99, 100, 101, 102, 103, 104, 103, 102, 101, 100, 99, 98, 97, 96, 95, 96, 97],
    'Close': [100, 101, 102, 103, 104, 105, 104, 103, 102, 101, 100, 99, 98, 97, 96, 97, 98],
    'Volume': [1000, 1200, 1300, 1100, 1400, 1500, 1200, 1300, 1400, 1100, 1200, 1300, 1400, 1500, 1200, 1300, 1400],
    'SMA_10': [99, 99.5, 100, 100.5, 101, 101.5, 101.2, 100.9, 100.6, 100.3, 100, 99.7, 99.4, 99.1, 98.8, 98.9, 99],
    'SMA_20': [98, 98.5, 99, 99.5, 100, 100.5, 100.3, 100.1, 99.9, 99.7, 99.5, 99.3, 99.1, 98.9, 98.7, 98.8, 98.9],
}

In [3]:
#딕셔너리에서 꼭 dataframe화 해주기

In [4]:
import pandas as pd

In [5]:
_myDf = pd.DataFrame(_ohlcv, index=pd.date_range('2024-10-01', periods=17))

In [6]:
_myDf

            Open  High  Low  Close  Volume  SMA_10  SMA_20
2024-10-01   100   101   99    100    1000    99.0    98.0
2024-10-02   101   102  100    101    1200    99.5    98.5
2024-10-03   102   103  101    102    1300   100.0    99.0
2024-10-04   103   104  102    103    1100   100.5    99.5
2024-10-05   104   105  103    104    1400   101.0   100.0
2024-10-06   105   106  104    105    1500   101.5   100.5
2024-10-07   104   105  103    104    1200   101.2   100.3
2024-10-08   103   104  102    103    1300   100.9   100.1
2024-10-09   102   103  101    102    1400   100.6    99.9
2024-10-10   101   102  100    101    1100   100.3    99.7
2024-10-11   100   101   99    100    1200   100.0    99.5
2024-10-12    99   100   98     99    1300    99.7    99.3
2024-10-13    98    99   97     98    1400    99.4    99.1
2024-10-14    97    98   96     97    1500    99.1    98.9
2024-10-15    96    97   95     96    1200    98.8    98.7
2024-10-16    97    98   96     97    1300    98.9    98.8
2024-10-17    98    99   97     98    1400    99.0    98.9

In [10]:
_myDf['Close-1'] = _myDf['Close'].shift(-1)
_myDf['Target'] = (_myDf['Close'].shift(-1) > _myDf['Close']).astype(int)

#shift는 한 줄 내릴때 사용하는 건데 여기서는 -1이니까 한 줄 올린 거얌

In [8]:
#data를 보고 상승했는지 하강했는지 Target 변수를 이용하여 이분화 가능

In [9]:
_myDf

            Open  High  Low  Close  Volume  SMA_10  SMA_20  Close-1  Target
2024-10-01   100   101   99    100    1000    99.0    98.0    101.0       1
2024-10-02   101   102  100    101    1200    99.5    98.5    102.0       1
2024-10-03   102   103  101    102    1300   100.0    99.0    103.0       1
2024-10-04   103   104  102    103    1100   100.5    99.5    104.0       1
2024-10-05   104   105  103    104    1400   101.0   100.0    105.0       1
2024-10-06   105   106  104    105    1500   101.5   100.5    104.0       0
2024-10-07   104   105  103    104    1200   101.2   100.3    103.0       0
2024-10-08   103   104  102    103    1300   100.9   100.1    102.0       0
2024-10-09   102   103  101    102    1400   100.6    99.9    101.0       0
2024-10-10   101   102  100    101    1100   100.3    99.7    100.0       0
2024-10-11   100   101   99    100    1200   100.0    99.5     99.0       0
2024-10-12    99   100   98     99    1300    99.7    99.3     98.0       0
2024-10-13    98    99   97     98    1400    99.4    99.1     97.0       0
2024-10-14    97    98   96     97    1500    99.1    98.9     96.0       0
2024-10-15    96    97   95     96    1200    98.8    98.7     97.0       1
2024-10-16    97    98   96     97    1300    98.9    98.8     98.0       1
2024-10-17    98    99   97     98    1400    99.0    98.9      NaN       0

In [16]:
# close와 close-1을 보고 알 수 있음
#여기서 문제는 제일 마지막줄에 NaN이 있다는 것임

In [17]:
features = ['SMA_10', 'SMA_20']

In [18]:
features

['SMA_10', 'SMA_20']

In [19]:
X = _myDf[features]

In [20]:
X

            SMA_10  SMA_20
2024-10-01    99.0    98.0
2024-10-02    99.5    98.5
2024-10-03   100.0    99.0
2024-10-04   100.5    99.5
2024-10-05   101.0   100.0
2024-10-06   101.5   100.5
2024-10-07   101.2   100.3
2024-10-08   100.9   100.1
2024-10-09   100.6    99.9
2024-10-10   100.3    99.7
2024-10-11   100.0    99.5
2024-10-12    99.7    99.3
2024-10-13    99.4    99.1
2024-10-14    99.1    98.9
2024-10-15    98.8    98.7
2024-10-16    98.9    98.8
2024-10-17    99.0    98.9

In [21]:
y = _myDf['Target']

In [22]:
y

2024-10-01    1
2024-10-02    1
2024-10-03    1
2024-10-04    1
2024-10-05    1
2024-10-06    0
2024-10-07    0
2024-10-08    0
2024-10-09    0
2024-10-10    0
2024-10-11    0
2024-10-12    0
2024-10-13    0
2024-10-14    0
2024-10-15    1
2024-10-16    1
2024-10-17    0
Freq: D, Name: Target, dtype: int32

그래서 제일 간단한 방법을 쓰기로 함
그냥 제일 밑에 17일자를 자르는 것임

In [24]:
features = ['SMA_10', 'SMA_20']
X = _myDf[features].iloc[:-1]  # [:-1] --> 마지막 줄 제외, features만 선별 (Close 제외)
y = _myDf['Target'].iloc[:-1]  # [:-1] --> 마지막 줄 제외

In [25]:
X

            SMA_10  SMA_20
2024-10-01    99.0    98.0
2024-10-02    99.5    98.5
2024-10-03   100.0    99.0
2024-10-04   100.5    99.5
2024-10-05   101.0   100.0
2024-10-06   101.5   100.5
2024-10-07   101.2   100.3
2024-10-08   100.9   100.1
2024-10-09   100.6    99.9
2024-10-10   100.3    99.7
2024-10-11   100.0    99.5
2024-10-12    99.7    99.3
2024-10-13    99.4    99.1
2024-10-14    99.1    98.9
2024-10-15    98.8    98.7
2024-10-16    98.9    98.8

In [26]:
y

2024-10-01    1
2024-10-02    1
2024-10-03    1
2024-10-04    1
2024-10-05    1
2024-10-06    0
2024-10-07    0
2024-10-08    0
2024-10-09    0
2024-10-10    0
2024-10-11    0
2024-10-12    0
2024-10-13    0
2024-10-14    0
2024-10-15    1
2024-10-16    1
Freq: D, Name: Target, dtype: int32

In [31]:
conda install scikit-learn

Retrieving notices: ...working... done
Channels:
 - defaults
 - anaconda
Platform: win-64
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\rkdus3696\anaconda3\envs\env3.9

  added / updated specs:
    - scikit-learn


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2024.11.26 |       haa95532_0         132 KB
    joblib-1.4.2               |   py39haa95532_0         398 KB
    scikit-learn-1.5.1         |   py39hc64d2fc_0         8.3 MB
    scipy-1.13.1               |   py39h8640f81_0        25.4 MB
    threadpoolctl-3.5.0        |   py39h9909e9c_0          43 KB
    ------------------------------------------------------------
                                           Total:        34.2 MB

The following NEW packages will be INSTALLED:

  icc_rt             pkgs/main/win-64::icc_rt-2022.1.0-h6049295_2
  joblib             pkgs/main/win-64::joblib-1.4.2-py39haa95532_0
  pybind11-abi       pkgs/main/noarch::pybind11-abi-5-hd3eb1b0_0
  scikit-learn       pkgs/main/win-64::scikit-learn-1.5.1-py39hc64d2fc_0
  scipy              pkgs/main/win-64::scipy-1.13.1-py39h8640f81_0
  threadpoolctl      pkgs/main/win-64::threadpoolctl-3.5.0-py39h9909e9c_0

The following packages will be UPDATED:

  ca-certificates                      2024.9.24-haa95532_0 --> 2024.11.26-haa95532_0



Downloading and Extracting Packages: ...working... done
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done

Note: you may need to restart the kernel to use updated packages.

In [33]:
!pip install -U scikit-learn

Requirement already satisfied: scikit-learn in c:\users\rkdus3696\anaconda3\envs\env3.9\lib\site-packages (1.5.1)
Collecting scikit-learn
  Downloading scikit_learn-1.5.2-cp39-cp39-win_amd64.whl.metadata (13 kB)
Requirement already satisfied: numpy>=1.19.5 in c:\users\rkdus3696\anaconda3\envs\env3.9\lib\site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in c:\users\rkdus3696\anaconda3\envs\env3.9\lib\site-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\rkdus3696\anaconda3\envs\env3.9\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\rkdus3696\anaconda3\envs\env3.9\lib\site-packages (from scikit-learn) (3.5.0)
Downloading scikit_learn-1.5.2-cp39-cp39-win_amd64.whl (11.0 MB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   -- ------------------------------------- 0.8/11.0 MB 8.3 MB/s eta 0:00:02
   ------- -------------------------------- 2.1/11.0 MB 6.2 MB/s eta 0:00:02
   -------- ------------------------------- 2.4/11.0 MB 4.2 MB/s eta 0:00:03
   -------- ------------------------------- 2.4/11.0 MB 4.2 MB/s eta 0:00:03
   -------- ------------------------------- 2.4/11.0 MB 4.2 MB/s eta 0:00:03
   ---------- ----------------------------- 2.9/11.0 MB 2.3 MB/s eta 0:00:04
   ------------ --------------------------- 3.4/11.0 MB 2.4 MB/s eta 0:00:04
   ------------- -------------------------- 3.7/11.0 MB 2.2 MB/s eta 0:00:04
   ------------- -------------------------- 3.7/11.0 MB 2.2 MB/s eta 0:00:04
   ------------- -------------------------- 3.7/11.0 MB 2.2 MB/s eta 0:00:04
   ------------- -------------------------- 3.7/11.0 MB 2.2 MB/s eta 0:00:04
   ----------------- ---------------------- 4.7/11.0 MB 1.9 MB/s eta 0:00:04
   ----------------- ---------------------- 4.7/11.0 MB 1.9 MB/s eta 0:00:04
   ----------------- ---------------------- 4.7/11.0 MB 1.9 MB/s eta 0:00:04
   ----------------- ---------------------- 4.7/11.0 MB 1.9 MB/s eta 0:00:04
   ----------------- ---------------------- 4.7/11.0 MB 1.9 MB/s eta 0:00:04
   ----------------- ---------------------- 4.7/11.0 MB 1.9 MB/s eta 0:00:04
   ----------------- ---------------------- 4.7/11.0 MB 1.9 MB/s eta 0:00:04
   ----------------- ---------------------- 4.7/11.0 MB 1.9 MB/s eta 0:00:04
   ----------------- ---------------------- 4.7/11.0 MB 1.9 MB/s eta 0:00:04
   ----------------- ---------------------- 4.7/11.0 MB 1.9 MB/s eta 0:00:04
   ----------------- ---------------------- 4.7/11.0 MB 1.9 MB/s eta 0:00:04
   ----------------- ---------------------- 4.7/11.0 MB 1.9 MB/s eta 0:00:04
   ----------------- ---------------------- 4.7/11.0 MB 1.9 MB/s eta 0:00:04
   ------------------ --------------------- 5.0/11.0 MB 946.6 kB/s eta 0:00:07
   ------------------- -------------------- 5.5/11.0 MB 1.0 MB/s eta 0:00:06
   ----------------------- ---------------- 6.6/11.0 MB 1.1 MB/s eta 0:00:04
   ------------------------- -------------- 7.1/11.0 MB 1.2 MB/s eta 0:00:04
   -------------------------- ------------- 7.3/11.0 MB 1.2 MB/s eta 0:00:04
   ---------------------------- ----------- 7.9/11.0 MB 1.2 MB/s eta 0:00:03
   ----------------------------- ---------- 8.1/11.0 MB 1.2 MB/s eta 0:00:03
   ------------------------------ --------- 8.4/11.0 MB 1.2 MB/s eta 0:00:03
   ------------------------------ --------- 8.4/11.0 MB 1.2 MB/s eta 0:00:03
   ------------------------------ --------- 8.4/11.0 MB 1.2 MB/s eta 0:00:03
   --------------------------------- ------ 9.2/11.0 MB 1.2 MB/s eta 0:00:02
   ---------------------------------- ----- 9.4/11.0 MB 1.2 MB/s eta 0:00:02
   ----------------------------------- ---- 9.7/11.0 MB 1.2 MB/s eta 0:00:02
   ------------------------------------ --- 10.0/11.0 MB 1.2 MB/s eta 0:00:01
   ------------------------------------- -- 10.2/11.0 MB 1.3 MB/s eta 0:00:01
   -------------------------------------- - 10.5/11.0 MB 1.3 MB/s eta 0:00:01
   -------------------------------------- - 10.7/11.0 MB 1.2 MB/s eta 0:00:01
   ---------------------------------------- 11.0/11.0 MB 1.2 MB/s eta 0:00:00
Installing collected packages: scikit-learn
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.5.1
    Uninstalling scikit-learn-1.5.1:
      Successfully uninstalled scikit-learn-1.5.1
Successfully installed scikit-learn-1.5.2

In [34]:
import sklearn
from sklearn.model_selection import train_test_split
#학습시키는 방법

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [38]:
from sklearn.ensemble import RandomForestClassifier

#randomforest를 이용한 분류
model = RandomForestClassifier(n_estimators=100, random_state=42)

In [39]:
#모델 학습시키기

model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [40]:
#모델에 test data 넣어보기

y_pred = model.predict(X_test)

In [41]:
X_test['Prediction'] = y_pred

#test data로 값 예측하기

In [42]:
print(f"테스트본: {X_test}")

테스트본:             SMA_10  SMA_20  Prediction
2024-10-01    99.0    98.0           1
2024-10-02    99.5    98.5           1
2024-10-06   101.5   100.5           0
2024-10-15    98.8    98.7           1
2024-10-14    99.1    98.9           1

In [50]:
print(f"원본: {_myDf}")

원본:             Open  High  Low  Close  Volume  SMA_10  SMA_20  Close-1  Target
2024-10-01   100   101   99    100    1000    99.0    98.0    101.0       1
2024-10-02   101   102  100    101    1200    99.5    98.5    102.0       1
2024-10-03   102   103  101    102    1300   100.0    99.0    103.0       1
2024-10-04   103   104  102    103    1100   100.5    99.5    104.0       1
2024-10-05   104   105  103    104    1400   101.0   100.0    105.0       1
2024-10-06   105   106  104    105    1500   101.5   100.5    104.0       0
2024-10-07   104   105  103    104    1200   101.2   100.3    103.0       0
2024-10-08   103   104  102    103    1300   100.9   100.1    102.0       0
2024-10-09   102   103  101    102    1400   100.6    99.9    101.0       0
2024-10-10   101   102  100    101    1100   100.3    99.7    100.0       0
2024-10-11   100   101   99    100    1200   100.0    99.5     99.0       0
2024-10-12    99   100   98     99    1300    99.7    99.3     98.0       0
2024-10-13    98    99   97     98    1400    99.4    99.1     97.0       0
2024-10-14    97    98   96     97    1500    99.1    98.9     96.0       0
2024-10-15    96    97   95     96    1200    98.8    98.7     97.0       1
2024-10-16    97    98   96     97    1300    98.9    98.8     98.0       1
2024-10-17    98    99   97     98    1400    99.0    98.9      NaN       0

In [51]:
#원본에서도 1, 2, 6, 15, 14만 뽑고싶음.. Q

In [52]:
model.predict(X)

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1])