In [ ]:
s/ds3_stockQuant.ipynb

In [ ]:
7.1 기계학습 RandomForest

In [ ]:
https://github.com/smu405/s/blob/master/ds3_stockQuant.ipynb

In [1]:
#기계학습 + 스파크

In [2]:
#기계학습

In [3]:
'''



features 의 셩격을 파악하기
    -> 표로 case 나누기
    
색  겉  크기
R  매끈  6         ->사과
Y  거침  7         ->오렌지           => 사전에 레이블 작업(=태깅) -> 머신러닝에 도입 -> 학습 
                                            이때 태깅이 된(정답을 알려준) 학습을 지도학습이라고 한다


분류 ) 1] 이진 분류
            X  그외
       2] 다중 분류
            0 1 2 => 이런식
            
            
-> 특징을 이용하여 답(=label)(=class) 도출 

레이블이 없다 -> 비지도학습

특징 ----------> [ML] ----------> target(=class)(=label)(=결과값)

이때 머신러닝에서 하는 게 '모델링'
y : 레이블
y = f(x)로 표현이 가능하다

****이때 x는 특징(변수)*****
---------------> 다중이면 x1 x2 x3 로 표현
                    이 앞에 weight를 붙여준다
                    w1x1+w2x2+w3x3+감마
                                -> linear(선형) 모델
                                
                    비선형모델 => wqx1*w2x2*w3x3+감마
    
    
    
    
'''

"\n\n\n\nfeatures 의 셩격을 파악하기\n    -> 표로 case 나누기\n    \n색  겉  크기\nR  매끈  6         ->사과\nY  거침  7         ->오렌지           => 사전에 레이블 작업(=태깅) -> 머신러닝에 도입 -> 학습 \n                                            이때 태깅이 된(정답을 알려준) 학습을 지도학습이라고 한다\n\n\n분류 ) 1] 이진 분류\n            X  그외\n       2] 다중 분류\n            0 1 2 => 이런식\n            \n            \n-> 특징을 이용하여 답(=label)(=class) 도출 \n\n레이블이 없다 -> 비지도학습\n\n특징 ----------> [ML] ----------> target(=class)(=label)(=결과값)\n\n이때 머신러닝에서 하는 게 '모델링'\ny : 레이블\ny = f(x)로 표현이 가능하다\n\n****이때 x는 특징(변수)*****\n---------------> 다중이면 x1 x2 x3 로 표현\n                    이 앞에 weight를 붙여준다\n                    w1x1+w2x2+w3x3+감마\n                                -> linear(선형) 모델\n                                \n                    비선형모델 => wqx1*w2x2*w3x3+감마\n    \n    \n    \n    \n"

In [4]:
#기계 학습을 백테스팅에 적용
#RandomFores

In [5]:
#백테스팅은 모델이 데이터로부터 학습한 신호(-> 신호는 여러개일 수 있다 ex] 오른다 안 오른다 엄청 오른다

In [6]:
#1. 속성 및 레이블 준비 == 특징 추출하기 -> data가공

In [7]:
#정서지표 sentiment(=정서) 긍/부정의 이진분류 ex) 호/불호

In [8]:
#특징은 실제값일 수 있다 (명목)

In [9]:
#모델 훈련

In [10]:
#랜덤 포레스트

In [11]:
#convination -> 여러 결과값을 정보를 받아서 평균내기

In [12]:
# -> tree응ㄹ===를 여러개 묶어서

In [13]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\rkdus3696\miniconda\lib\site-packages (1.5.2)
Requirement already satisfied: numpy>=1.19.5 in c:\users\rkdus3696\miniconda\lib\site-packages (from scikit-learn) (2.1.1)
Requirement already satisfied: scipy>=1.6.0 in c:\users\rkdus3696\miniconda\lib\site-packages (from scikit-learn) (1.14.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\rkdus3696\miniconda\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\rkdus3696\miniconda\lib\site-packages (from scikit-learn) (3.5.0)

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score #정확성

In [3]:
_ohlcv = {
        'Open': [100, 101, 102, 103, 104, 105, 104, 103, 102, 101, 100, 99, 98, 97, 96, 97, 98],
    'High': [101, 102, 103, 104, 105, 106, 105, 104, 103, 102, 101, 100, 99, 98, 97, 98, 99],
    'Low': [99, 100, 101, 102, 103, 104, 103, 102, 101, 100, 99, 98, 97, 96, 95, 96, 97],
    'Close': [100, 101, 102, 103, 104, 105, 104, 103, 102, 101, 100, 99, 98, 97, 96, 97, 98],
    'Volume': [1000, 1200, 1300, 1100, 1400, 1500, 1200, 1300, 1400, 1100, 1200, 1300, 1400, 1500, 1200, 1300, 1400],
    'SMA_10': [99, 99.5, 100, 100.5, 101, 101.5, 101.2, 100.9, 100.6, 100.3, 100, 99.7, 99.4, 99.1, 98.8, 98.9, 99],
    'SMA_20': [98, 98.5, 99, 99.5, 100, 100.5, 100.3, 100.1, 99.9, 99.7, 99.5, 99.3, 99.1, 98.9, 98.7, 98.8, 98.9],
}

In [4]:
#딕셔너리 -> dataframe

In [5]:
'''

colum에 dataframe이 있는지 없는지가 중요
프로그래밍 할 때 하나하나 다 이해하는게 중요
dataframe이 안 되는 경우, 하는 방법 중요

'''

'\n\ncolum에 dataframe이 있는지 없는지가 중요\n프로그래밍 할 때 하나하나 다 이해하는게 중요\ndataframe이 안 되는 경우, 하는 방법 중요\n\n'

In [6]:
_myDf = pd.DataFrame(_ohlcv, index=pd.date_range('2024-10-01', periods=17))

In [7]:
#날짜 번호 date_range => 17개의 data

In [8]:
#일자별로 있어야 시계열 data

In [9]:
#날짜를 넣으면 간편하게 구현 가능해서 날짜를 대입

In [10]:
#SMA_10, SMA20을 features로 사용할 예정

In [11]:
#y(=100)(=close[1]) = f (99(=sma10),98(=sma20))
#               but 다른 값도 사용 가능하다

In [12]:
#여기선 이진라벨을 할 것이다(많이 적용됨)

In [13]:
#상승하는지 하강하는지 -> 이전 값을 고려하면 된다

In [14]:
_myDf['Close-1'] = _myDf['Close'].shift(-1)
_myDf['Target'] = (_myDf['Close'].shift(-1) > _myDf['Close']).astype(int) # 상승 1, 아니면 0으로 이분화

In [15]:
#shift함수 -> 밑으로 한 줄 내릴때 (1)을 사용
# 여기서 종가 한줄을 내리면 이전 값일 것 -1이면 한줄 올리는 거임

In [16]:
_myDf

            Open  High  Low  Close  Volume  SMA_10  SMA_20  Close-1  Target
2024-10-01   100   101   99    100    1000    99.0    98.0    101.0       1
2024-10-02   101   102  100    101    1200    99.5    98.5    102.0       1
2024-10-03   102   103  101    102    1300   100.0    99.0    103.0       1
2024-10-04   103   104  102    103    1100   100.5    99.5    104.0       1
2024-10-05   104   105  103    104    1400   101.0   100.0    105.0       1
2024-10-06   105   106  104    105    1500   101.5   100.5    104.0       0
2024-10-07   104   105  103    104    1200   101.2   100.3    103.0       0
2024-10-08   103   104  102    103    1300   100.9   100.1    102.0       0
2024-10-09   102   103  101    102    1400   100.6    99.9    101.0       0
2024-10-10   101   102  100    101    1100   100.3    99.7    100.0       0
2024-10-11   100   101   99    100    1200   100.0    99.5     99.0       0
2024-10-12    99   100   98     99    1300    99.7    99.3     98.0       0
2024-10-13    98    99   97     98    1400    99.4    99.1     97.0       0
2024-10-14    97    98   96     97    1500    99.1    98.9     96.0       0
2024-10-15    96    97   95     96    1200    98.8    98.7     97.0       1
2024-10-16    97    98   96     97    1300    98.9    98.8     98.0       1
2024-10-17    98    99   97     98    1400    99.0    98.9      NaN       0

In [17]:
#여기까지 속성과 레이블 세팅

In [18]:
#NaN을 해결해야함

In [19]:
features = ['SMA_10', 'SMA_20']
X = _myDf[features].iloc[:-1]  # [:-1] --> 마지막 줄 제외, features만 선별 (Close 제외)
y = _myDf['Target'].iloc[:-1]  # [:-1] --> 마지막 줄 제외

In [20]:
#파이썬에서는 sklearn을 많이 쓴다

In [21]:
#features가 어떤 값인지 고려해야한다 ex) 명목변수, 순위변수, 연속변수 등등

In [22]:
#명목변수는 계산이 아니라서 별도의 취급을 해야해서 고려해야함but이건 연속이라서 괜찮다

In [23]:
#벡터로 묶을 땐 보통 X를 사용한다
#iloc 인티저 방법으로 인덱싱하겠다는 것 
#NAN때문에 -1을 이용하여 마지막을 빼줌

In [24]:
X

            SMA_10  SMA_20
2024-10-01    99.0    98.0
2024-10-02    99.5    98.5
2024-10-03   100.0    99.0
2024-10-04   100.5    99.5
2024-10-05   101.0   100.0
2024-10-06   101.5   100.5
2024-10-07   101.2   100.3
2024-10-08   100.9   100.1
2024-10-09   100.6    99.9
2024-10-10   100.3    99.7
2024-10-11   100.0    99.5
2024-10-12    99.7    99.3
2024-10-13    99.4    99.1
2024-10-14    99.1    98.9
2024-10-15    98.8    98.7
2024-10-16    98.9    98.8

입력 - 함수 -> 출력

이중에 함수를 할 것

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

#train_test_split 이용하였음 -> 이 함수를 이용하기 위해서 앞에 함수를 정의했었음

In [26]:
#제일 마지막 42의 시드 번호는 아무거나 써도 돼

In [27]:
model = RandomForestClassifier(n_estimators=100, random_state=42)
#tree가 나오면 무작위로 학습하세요
#생성 tree의 갯수 100개

In [28]:
#모델에 적용시킨 것 이것도 import로 정의했었어요

In [29]:
#model 이라서 Class라서 Random 앞에가 대문자임

In [30]:
#tree를 여러개로 묶어서 Forest

In [31]:
#x를 맞추는 부분이 test 여기서는 predict()함수를 많이 쓴다
#그 위에 이ㅆ는 값을 train이라고 하고 train에서 fit()함수를 많이 씀

In [32]:
#fit => 최적화를 찾는 train

In [33]:
#predict => 예측을 하는 test

In [34]:
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [35]:
#fit data에서 형식을 맞춰줘야함 여긴 2차원 배열이다

In [36]:
#여기까지 모델이 만들어 진 것

In [37]:
y_pred = model.predict(X_test) # 테스트데이터에 모델 적용

In [38]:
#test data로 예측하기 (실제 데이터)

In [40]:
X_test['Prediction'] = y_pred # X_test에 예측 컬럼을 추가
print(f"테스트본: {X_test}")
print(f"원본: {_myDf}")

테스트본:             SMA_10  SMA_20  Prediction
2024-10-01    99.0    98.0           1
2024-10-02    99.5    98.5           1
2024-10-06   101.5   100.5           0
2024-10-15    98.8    98.7           1
2024-10-14    99.1    98.9           1
원본:             Open  High  Low  Close  Volume  SMA_10  SMA_20  Close-1  Target
2024-10-01   100   101   99    100    1000    99.0    98.0    101.0       1
2024-10-02   101   102  100    101    1200    99.5    98.5    102.0       1
2024-10-03   102   103  101    102    1300   100.0    99.0    103.0       1
2024-10-04   103   104  102    103    1100   100.5    99.5    104.0       1
2024-10-05   104   105  103    104    1400   101.0   100.0    105.0       1
2024-10-06   105   106  104    105    1500   101.5   100.5    104.0       0
2024-10-07   104   105  103    104    1200   101.2   100.3    103.0       0
2024-10-08   103   104  102    103    1300   100.9   100.1    102.0       0
2024-10-09   102   103  101    102    1400   100.6    99.9    101.0       0
2024-10-10   101   102  100    101    1100   100.3    99.7    100.0       0
2024-10-11   100   101   99    100    1200   100.0    99.5     99.0       0
2024-10-12    99   100   98     99    1300    99.7    99.3     98.0       0
2024-10-13    98    99   97     98    1400    99.4    99.1     97.0       0
2024-10-14    97    98   96     97    1500    99.1    98.9     96.0       0
2024-10-15    96    97   95     96    1200    98.8    98.7     97.0       1
2024-10-16    97    98   96     97    1300    98.9    98.8     98.0       1
2024-10-17    98    99   97     98    1400    99.0    98.9      NaN       0

In [41]:
#무작위로 섞은 test data

In [42]:
model.predict(X)

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1])

In [43]:
#전체의 태깅값을 확인할 수 있다! 
#실제 data의 태깅값 (=정답값)

In [44]:
model.predict(_myDf[features])

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1])

In [46]:
y_predAll = model.predict(_myDf[features])


_myDfCopy = _myDf.copy()
_myDfCopy.loc[_myDfCopy.index, '

In [45]:
y_predAll = model.predict(_myDf[features]) #y_predAll = model.predict(X)

# 원본에 추가할 수도 있다. 나중에 백테스트데이터로 쓰기 위해 복사본을 만들자.
_myDfCopy = _myDf.copy()
_myDfCopy.loc[_myDfCopy.index, 'Prediction'] = y_predAll # 원본하고 합침

print(f"합본:\n {_myDfCopy}")

# 정확성 = 맞은 갯수/전체
print(f"Test Accuracy: {accuracy_score(y_test, y_pred)}")

합본:
             Open  High  Low  Close  Volume  SMA_10  SMA_20  Close-1  Target  \
2024-10-01   100   101   99    100    1000    99.0    98.0    101.0       1
2024-10-02   101   102  100    101    1200    99.5    98.5    102.0       1
2024-10-03   102   103  101    102    1300   100.0    99.0    103.0       1
2024-10-04   103   104  102    103    1100   100.5    99.5    104.0       1
2024-10-05   104   105  103    104    1400   101.0   100.0    105.0       1
2024-10-06   105   106  104    105    1500   101.5   100.5    104.0       0
2024-10-07   104   105  103    104    1200   101.2   100.3    103.0       0
2024-10-08   103   104  102    103    1300   100.9   100.1    102.0       0
2024-10-09   102   103  101    102    1400   100.6    99.9    101.0       0
2024-10-10   101   102  100    101    1100   100.3    99.7    100.0       0
2024-10-11   100   101   99    100    1200   100.0    99.5     99.0       0
2024-10-12    99   100   98     99    1300    99.7    99.3     98.0       0
2024-10-13    98    99   97     98    1400    99.4    99.1     97.0       0
2024-10-14    97    98   96     97    1500    99.1    98.9     96.0       0
2024-10-15    96    97   95     96    1200    98.8    98.7     97.0       1
2024-10-16    97    98   96     97    1300    98.9    98.8     98.0       1
2024-10-17    98    99   97     98    1400    99.0    98.9      NaN       0

            Prediction
2024-10-01         1.0
2024-10-02         1.0
2024-10-03         1.0
2024-10-04         1.0
2024-10-05         1.0
2024-10-06         0.0
2024-10-07         0.0
2024-10-08         0.0
2024-10-09         0.0
2024-10-10         0.0
2024-10-11         0.0
2024-10-12         0.0
2024-10-13         0.0
2024-10-14         1.0
2024-10-15         1.0
2024-10-16         1.0
2024-10-17         1.0
Test Accuracy: 0.8

In [57]:
#30%의 이점을 얻을 수 있으니 효율적이라는 것

In [58]:
#1 -> 오를 것으로 예측 --> 구매

In [59]:
#0 -> 내릴 것으로 예측 --> 판매

In [60]:
#모델 저장
#메모리 -> 하드디스크에 저장
#파일 이름.피클 --> 여기서 피클은 꼭 맞춰줘야 한다 --> 바이너리를 저장할때 피클 방식으로 저장하기 때문

import joblib
joblib.dump(model, 'knn_model.pkl')

['knn_model.pkl']

In [61]:
#이렇게 해두면 다시 훈련하지 않아도 된다

In [62]:
pip install Backtesting

Requirement already satisfied: Backtesting in c:\users\rkdus3696\miniconda\lib\site-packages (0.3.3)
Requirement already satisfied: numpy>=1.17.0 in c:\users\rkdus3696\miniconda\lib\site-packages (from Backtesting) (2.1.1)
Requirement already satisfied: pandas!=0.25.0,>=0.25.0 in c:\users\rkdus3696\miniconda\lib\site-packages (from Backtesting) (2.2.3)
Requirement already satisfied: bokeh>=1.4.0 in c:\users\rkdus3696\miniconda\lib\site-packages (from Backtesting) (3.6.0)
Requirement already satisfied: Jinja2>=2.9 in c:\users\rkdus3696\miniconda\lib\site-packages (from bokeh>=1.4.0->Backtesting) (3.1.4)
Requirement already satisfied: contourpy>=1.2 in c:\users\rkdus3696\miniconda\lib\site-packages (from bokeh>=1.4.0->Backtesting) (1.3.0)
Requirement already satisfied: packaging>=16.8 in c:\users\rkdus3696\miniconda\lib\site-packages (from bokeh>=1.4.0->Backtesting) (23.0)
Requirement already satisfied: pillow>=7.1.0 in c:\users\rkdus3696\miniconda\lib\site-packages (from bokeh>=1.4.0->Backtesting) (10.4.0)
Requirement already satisfied: PyYAML>=3.10 in c:\users\rkdus3696\miniconda\lib\site-packages (from bokeh>=1.4.0->Backtesting) (6.0.2)
Requirement already satisfied: tornado>=6.2 in c:\users\rkdus3696\miniconda\lib\site-packages (from bokeh>=1.4.0->Backtesting) (6.4.1)
Requirement already satisfied: xyzservices>=2021.09.1 in c:\users\rkdus3696\miniconda\lib\site-packages (from bokeh>=1.4.0->Backtesting) (2024.9.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\rkdus3696\miniconda\lib\site-packages (from pandas!=0.25.0,>=0.25.0->Backtesting) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\rkdus3696\miniconda\lib\site-packages (from pandas!=0.25.0,>=0.25.0->Backtesting) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\rkdus3696\miniconda\lib\site-packages (from pandas!=0.25.0,>=0.25.0->Backtesting) (2024.2)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\rkdus3696\miniconda\lib\site-packages (from Jinja2>=2.9->bokeh>=1.4.0->Backtesting) (2.1.5)
Requirement already satisfied: six>=1.5 in c:\users\rkdus3696\miniconda\lib\site-packages (from python-dateutil>=2.8.2->pandas!=0.25.0,>=0.25.0->Backtesting) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [48]:
from backtesting import Backtest, Strategy
from backtesting.lib import crossover
import pandas as pd

ModuleNotFoundError: No module named 'bokeh'

In [ ]:
#전략 class적용

class MLStrategy(Strategy):
    def init(self):
        self.pred = self.data.df['Prediction'].values
        
        
    #print는 반복문 안에 있으니까 print로 계속 출력해 보는 것을 추천한다
    
    def next(self):
        idx = len(self.data) - 1
        _pred = self.pred[idx]
        _close = self.data.Close[-1]
        # Buy if model predicts price will go up
        print(f"[--] 예측: {_pred} {self.pred[-1]} 일자: {self.data.index[-1]} 직전보유: {self.position.size} 종가: {_close} 보유자금: {self.equity:.1f}")
        #if self.pred[-1] == 1 not self.position:
        #1이면 사고
        if _pred == 1 and not self.position:
                print(f"[+매수] 예측: {_pred} 일자:{self.data.index[-1]} 직전보유: {self.position.size} 종가: {_close} 보유자금: {self.equity:.1f}")
                self.buy()
        #elif self.pred[-1] == 0 and self.position:
        #0이면 팔게
        elif _pred == 0 and self.position:
                print(f"[-청산] 예측: {_pred} 일자:{self.data.index[-1]} 직전보유: {self.position.size} 종가: {_close} 보유자금: {self.equity:.1f}")
                #self.sell() #position
                self.position.close()

#data 가져오고
_myDfBacktest = _myDfCopy
#제일 뒤 열이 pred인 걸 기억하기
bt = Backtest(_myDfBacktest, MLStrategy, cash=10000, commission=.002) # increase cash
stats = bt.run()
print(stats)
bt.plot()


#수익률
#Return (Ann.) [%]                  115.491076

#인덱스

행의 data들은 data를 참조하는 게 윈도우방식(슬라이딩) 보통 주어지는 data는 이렇게 주어짐
이동하면서 다루는 거
그리고 SMA10,20,pred는 다 보통의 데이터 형태임 -> 일반적인 data취급보통 data는 0부터 인덱스가 시작한다
??????? 그럼 윈도우는 1부터 시작한다는 건가?  -> -1을 이용하여 최근 걸 보는 방식

In [ ]:
#복리 계산은 log를 이용

self.position.close() vs self.sell():
    
    전량매도 (window x 와 같음) vs 한줄씩 매도 
    close와 sell의 차이

In [65]:
#저장해둔 모델 불러서 계산하기

In [66]:
from backtesting import Backtest, Strategy
from backtesting.lib import crossover
import pandas as pd
import joblib

class MLStrategy(Strategy):
    def init(self):
        self.clf = joblib.load('knn_model.pkl') # 저장한 모델 joblib.dump(clf, 'knn_model.pkl') 불러기기
        X = self.data.df[['SMA_10', 'SMA_20']] # .df[[컬럼명]]으로 모델에 포함할 속성들 구성
        self.pred = pd.Series(self.clf.predict(X), index=self.data.index) # 일괄예측
    
    def next(self):
        _pred = self.pred.loc[self.data.index[-1]]  # -1??
        _close = self.data.Close[-1]
        print(f"[--] 예측: {_pred} 일자: {self.data.index[-1]} 직전보유: {self.position.size} 종가: {_close} 보유자금: {self.equity:.1f}")

        if _pred == 1 and not self.position:
                print(f"[+매수] 예측: {_pred} 일자:{self.data.index[-1]} 직전보유: {self.position.size} 종가: {_close} 보유자금: {self.equity:.1f}")
                self.buy()
        elif _pred == 0 and self.position:
                print(f"[-청산] 예측: {_pred} 일자:{self.data.index[-1]} 직전보유: {self.position.size} 종가: {_close} 보유자금: {self.equity:.1f}")
                #self.sell()
                self.position.close()

_myDfBacktest = _myDf.iloc[:-1].copy()  # Remove last row (no Target)
_myDfBacktest = _myDfCopy

bt = Backtest(_myDfBacktest, MLStrategy, cash=10000, commission=.002)
stats = bt.run()
print(stats)
bt.plot()

[--] 예측: 1 일자: 2024-10-02 00:00:00 직전보유: 0 종가: 101 보유자금: 10000.0
[+매수] 예측: 1 일자:2024-10-02 00:00:00 직전보유: 0 종가: 101 보유자금: 10000.0
[--] 예측: 1 일자: 2024-10-03 00:00:00 직전보유: 97 종가: 102 보유자금: 9980.2
[--] 예측: 1 일자: 2024-10-04 00:00:00 직전보유: 97 종가: 103 보유자금: 10077.2
[--] 예측: 1 일자: 2024-10-05 00:00:00 직전보유: 97 종가: 104 보유자금: 10174.2
[--] 예측: 0 일자: 2024-10-06 00:00:00 직전보유: 97 종가: 105 보유자금: 10271.2
[-청산] 예측: 0 일자:2024-10-06 00:00:00 직전보유: 97 종가: 105 보유자금: 10271.2
[--] 예측: 0 일자: 2024-10-07 00:00:00 직전보유: 0 종가: 104 보유자금: 10174.2
[--] 예측: 0 일자: 2024-10-08 00:00:00 직전보유: 0 종가: 103 보유자금: 10174.2
[--] 예측: 0 일자: 2024-10-09 00:00:00 직전보유: 0 종가: 102 보유자금: 10174.2
[--] 예측: 0 일자: 2024-10-10 00:00:00 직전보유: 0 종가: 101 보유자금: 10174.2
[--] 예측: 0 일자: 2024-10-11 00:00:00 직전보유: 0 종가: 100 보유자금: 10174.2
[--] 예측: 0 일자: 2024-10-12 00:00:00 직전보유: 0 종가: 99 보유자금: 10174.2
[--] 예측: 0 일자: 2024-10-13 00:00:00 직전보유: 0 종가: 98 보유자금: 10174.2
[--] 예측: 1 일자: 2024-10-14 00:00:00 직전보유: 0 종가: 97 보유자금: 10174.2
[+매수] 예측: 1 일자:2024-10-14 00:00:00 직전보유: 0 종가: 97 보유자금: 10174.2
[--] 예측: 1 일자: 2024-10-15 00:00:00 직전보유: 105 종가: 96 보유자금: 10154.1
[--] 예측: 1 일자: 2024-10-16 00:00:00 직전보유: 105 종가: 97 보유자금: 10259.1
[--] 예측: 1 일자: 2024-10-17 00:00:00 직전보유: 105 종가: 98 보유자금: 10364.1
Start                     2024-10-01 00:00:00
End                       2024-10-17 00:00:00
Duration                     16 days 00:00:00
Exposure Time [%]                   47.058824
Equity Final [$]                    10364.052
Equity Peak [$]                     10364.052
Return [%]                            3.64052
Buy & Hold Return [%]                    -2.0
Return (Ann.) [%]                  115.491076
Volatility (Ann.) [%]               23.922341
Sharpe Ratio                          4.82775
Sortino Ratio                       24.547772
Calmar Ratio                       101.249003
Max. Drawdown [%]                   -1.140664
Avg. Drawdown [%]                   -0.669272
Max. Drawdown Duration       11 days 00:00:00
Avg. Drawdown Duration        7 days 00:00:00
# Trades                                    2
Win Rate [%]                            100.0
Best Trade [%]                       1.879574
Worst Trade [%]                       1.75727
Avg. Trade [%]                       1.818404
Max. Trade Duration           4 days 00:00:00
Avg. Trade Duration           3 days 00:00:00
Profit Factor                             NaN
Expectancy [%]                       1.818422
SQN                                 23.294855
_strategy                          MLStrategy
_equity_curve                            E...
_trades                      Size  EntryBa...
dtype: object

ValueError: failed to validate DatetimeTickFormatter(id='p1092', ...).days: expected a value of type str, got ['%d %b', '%a %d'] of type list

In [67]:
#여기까진 이동 평균을 특징으로 썼다

In [68]:
#여긴 m l c d를 특징으로 삼아서 해보겠다

In [69]:
#특징만 바뀐 거임

In [70]:
#특징을 조절하는 것이 노하우

In [71]:
#ex 얼굴을 책정할때도 특징을 추출해서 하는 것

In [72]:
#어떤 특징을 중요하게 삼냐에 따라서 결과나 방법이 매우 다름

In [73]:
!dir data\sse2010_2024.csv

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 2A41-5FED

 C:\Users\rkdus3696\Code\202221389\env39\data 디렉터리

2024-10-24  오후 04:11           240,751 sse2010_2024.csv
               1개 파일             240,751 바이트
               0개 디렉터리  36,106,162,176 바이트 남음

In [74]:
#여기선 sse2010_2924를 정의하지 않았기 때문에 정의해줌

In [75]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from backtesting import Backtest, Strategy
import os
#from backtesting.test import EURUSD

sse2010_2024df=pd.read_csv(os.path.join('data','sse2010_2024.csv'), index_col=0, parse_dates=True)

data = sse2010_2024df.copy()

#ewm 지수이동평균
# MACD 지표 생성
#단기
data['EMA12'] = data['Close'].ewm(span=12, adjust=False).mean()
#중기
data['EMA26'] = data['Close'].ewm(span=26, adjust=False).mean()
data['MACD'] = data['EMA12'] - data['EMA26']
data['Signal'] = data['MACD'].ewm(span=9, adjust=False).mean()

# 기계학습을 위한 입력 데이터(X)와 타겟(y) 정의
data['X_MACD'] = data['MACD'] / data['Close']
data['X_Signal'] = data['Signal'] / data['Close']
data['Target'] = (data['Close'].shift(-1) > data['Close']).astype(int)

data.dropna(inplace=True) # NaN 제거

# 학습 데이터 준비
#기본 세팅은 동일하고 이게 달라진 것
X = data[['X_MACD', 'X_Signal']]
y = data['Target']

# 기계 학습 모델 학습
model = RandomForestClassifier(n_estimators=10, random_state=42)
model.fit(X, y)

class MACDMLStrategy(Strategy):
    def init(self):
        self.pred = pd.Series(model.predict(X), index=X.index) # 모델 바로 사용 (저장하지 않았다)
    
    def next(self):
        
        forecast = self.pred.loc[self.data.index[-1]] # 현재 위치 인덱스에 맞는 예측 값 가져오기

        if forecast == 1 and not self.position.is_long:
            self.buy()
        elif forecast == 0 and self.position.is_long:
            self.sell()

bt = Backtest(data, MACDMLStrategy, cash=10000, commission=.002)
stats = bt.run()
print(stats)
bt.plot()

C:\Users\rkdus3696\AppData\Local\Temp\ipykernel_21940\642065188.py:50: UserWarning: Some prices are larger than initial cash value. Note that fractional trading is not supported. If you want to trade Bitcoin, increase initial cash, or trade μBTC or satoshis instead (GH-134).
  bt = Backtest(data, MACDMLStrategy, cash=10000, commission=.002)

Start                     2010-01-04 00:00:00
End                       2024-07-19 00:00:00
Duration                   5310 days 00:00:00
Exposure Time [%]                         0.0
Equity Final [$]                      10000.0
Equity Peak [$]                       10000.0
Return [%]                                0.0
Buy & Hold Return [%]              421.631644
Return (Ann.) [%]                         0.0
Volatility (Ann.) [%]                     0.0
Sharpe Ratio                              NaN
Sortino Ratio                             NaN
Calmar Ratio                              NaN
Max. Drawdown [%]                        -0.0
Avg. Drawdown [%]                         NaN
Max. Drawdown Duration                    NaN
Avg. Drawdown Duration                    NaN
# Trades                                    0
Win Rate [%]                              NaN
Best Trade [%]                            NaN
Worst Trade [%]                           NaN
Avg. Trade [%]                            NaN
Max. Trade Duration                       NaN
Avg. Trade Duration                       NaN
Profit Factor                             NaN
Expectancy [%]                            NaN
SQN                                       NaN
_strategy                      MACDMLStrategy
_equity_curve                          Equ...
_trades                   Empty DataFrame
...
dtype: object

ValueError: failed to validate DatetimeTickFormatter(id='p1138', ...).days: expected a value of type str, got ['%d %b', '%a %d'] of type list

In [ ]:
#spark 는 하둡과 더불어 빅데이터를 분석하는데에 많이 쓰인다

In [ ]:
#빅데이터란? pandas란? 
#대량의 데이터 ==> 빅데이터 ==> 분산병렬처리

In [ ]:
#but! pandas는 분산병렬처리를 할 수 없다

In [ ]:
#병렬처리 frame이 필요! -> 동시에 여러가지를 수행할 수 있는 능력 (CPU가 여러개인 것 처럼)

In [ ]:
#특징은 text처리를 한다는 것이다

In [ ]:
#빅데이터 1]크기가 크고 2]판다스가 안 맞아서 하둡을 사용

In [ ]:
#판다스는 주로 숫자로 사용, 숫자 분석은 보통 통계고, text는 통계로 잘 안 먹힌다

In [ ]:
#통계는 숫자일때 주로 쓰는 전통적 방법

In [ ]:
#빅데이터는 text이기때문에 워드벡터라는 다른 기술을 사용해야 한다

In [ ]:
#한글을 아스키코드로 표현되어있고 이걸 워드 벡터라는 걸로 바꿔서 표현하는 기술의 개발
#워드 벡터 1) count 벡터              2)의미를 가진 벡터

In [76]:
#어떤 단어가 많이 쓰였는지 + 어떤 의미를 내포하는지

In [77]:
#둘 다 고려하는데 가까우면 동의어, 멀면 반어 등등으로 정의한다

In [78]:
#ex) 적 <       -      > 아군

In [79]:
#제일 발전한 거리 책정이 count벡터이다

In [80]:
#여기에 의미 기술까지 적용한게 현재의 chat gpt

In [81]:
#인공지능 VS ML

In [82]:
#ml은 기계가 학습하는 거 인공지능은 사람처럼 학습하는 UI 즉, 사람처럼 말하면 알아듣는 것

In [83]:
#open AI의 최종 도달점은 로봇이다

In [84]:
#주식분석은 숫자가지고 가능했다 -> 센티먼트 :: 이게 정서, text긴 했음!

In [85]:
#취업을 해야할 때 
#1) 프로그래밍 2)알고리즘

In [86]:
#자료구조 엄청 중요
#dataframe은 엑셀을 프로그래밍화
#RDD는 행열로 구성된 DF랑 다르게 (그릇에 넣는 형식과 다르게)
# 구조(=스키마)가 있다는 건 -> 행/열이 있다는 것
#data type란? 숫자랑 문자로 분류할 수 있다 + 0 1 (불리언)

In [87]:
#RDD는 스키마가 없고  DFQ는 스키마가 있음

In [88]:
#그래서 RDD는 맵리듀스를 한다 map.reduce! 빅데이터의 핵심 -> 이게 텍스트 처리하는 방법이다

In [89]:
#통계를 배우는 건 뭘까? --> 집단화!

In [90]:
#통계는 분포를 그린다 
#특정 data가 나타났을때 확률에 대해 이야기하곤 한다

In [91]:
#이러면 insight하게 파악이 가능

In [92]:
#ML에 넣는 건 feature
#ML의 출력은 1)정서분류 ex 긍/부정 or topic
#            2)

In [93]:
#rdd는 분산 병렬처리 -> so 실행방식이 2가지
# 1) 로컬방식 (==> PC)
# 2) C/S방식
#C/S방식을 완전 강강강추 but이건 완전 설치여서 로컬의 단순 설치를 일단 사용해보려고 함
#S는 서버에서 다루는 거라 완전 좋음
#클러스터 중요! ex) 아마존 ===> 컴퓨터가 여러대 (분산병렬처리 하는, data가 엄청 많은)
#로컬 방식도 크게 다르진 않음
#그냥 클러스터가 있다고 가정하고 하는 것
#클러스터에 배포하면 돼!! 명령문이 같으니까

In [94]:
#ds2_cloud 짧은 설명
#1) 데이터 브릭스(->스파크를 만든 회사) 아팟치(sw만드는 회사, 매우 중요한 오픈소스 보유 회사)
    # 여기서                             여기로 기부를 해서                     우린  data를 쓸 수 있음 아팟치 스파크 사용 가능
#2)구글 코랩

In [95]:
#!pip install pyspark
#py4j는 뭘까? -> py for j -> py for 자바

In [96]:
#https://spark.apache.org/downloads.html 참고 사이트, 여기서 다운로드 해야함

In [97]:
#자바설치 jdk 설치하기

In [98]:
#버전 충돌 문제가 있을 수 있으니 유의하기
#apache(유명한 SW)

In [99]:
#하둡도 아팟치에 있어서 자바도 다운해야하고 아팟치도 다운로드 해야해 -----> 매우 복잡함!! ---> 이게 완전 설치

In [100]:
#로컬이 원래 지원이 부실했는데 최근 잘 되어서 이번학기부터 로컬을 사용하겠음니다

In [ ]:
s
/ds4_spark_df.ipynb

In [ ]:
https://github.com/smu405/s/blob/master/ds4_spark_df.ipynb

In [101]:
#sparksession

In [102]:
#판다스보다 어려움

In [103]:
#이게 진입점으로 main함수와 같은 역학

#SparkContext, SQLContext, HiveContext 원래는 이렇게 개별적으로 context를 만들어서 썼음

In [104]:
#big data는 data와 기술을 많이 필요로 함

#꼭 기억해야할 내용

클러스터와의 인터페이스: Spark 클러스터에 접속하는 클라이언트 역할을 한다. 클러스터 매니저(YARN, Mesos, 
                                                            Kubernetes 등)와 통신해 작업을 스케줄링한다.
데이터 처리 및 분석: DataFrame API를 사용하거나, SQL 쿼리를 실행하고, RDD 변환과 같은 작업을 제공한다.
자원 관리: 클러스터 매니저(YARN, Mesos 등)로부터 CPU, 메모리와 같은 자원을 배분받아 작업을 수행한다.
            SparkSession을 사용하면 클러스터 매니저와 효율적으로 통합되어 자원 할당이 자동화된다.

In [105]:
#software 매니저 역할을 하는 3가지가 있음

In [106]:
#클러스터 -> 여러 컴퓨터에서 컴퓨터 자원을 각출해서 쓰는 것

In [107]:
#로컬 단순 설치 시작 -> site pakages 에 저장될 것

In [108]:
#디버깅도 어려워 이것저것 개입되는게 너무 많아서 ㅠㅠ

In [109]:
#우리의 옛 파이썬이랑 이 최신 버전들이랑 충돌이 일어날 수 있다는 걸 감안하기!

In [1]:
import sys
sys.executable

'C:\\Users\\rkdus3696\\miniconda\\python.exe'

In [2]:
#spark 만들기

In [3]:
pip install pyspark

Requirement already satisfied: pyspark in c:\users\rkdus3696\miniconda\lib\site-packages (3.5.3)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: py4j==0.10.9.7 in c:\users\rkdus3696\miniconda\lib\site-packages (from pyspark) (0.10.9.7)

In [4]:
#pip install findspark

In [5]:
import os, sys
import pyspark

#environ -> 환경설정! path 설정! 환경변수 설치의 기능을 한다
#기계를 여러개 쓸건데 기계별로 버전을 맞춰주기 위해 각각을 설치한다~ 가끔 설치 안 해도 되긴 하는데 일단 합시다
os.environ["PYSPARK_PYTHON"]=sys.executable          # 현재 사용 중인 Python 실행 파일 경로 설정 (리눅스 "/usr/bin/python3")
os.environ["PYSPARK_DRIVER_PYTHON"]=sys.executable   # Driver에서도 동일한 Python 경로 설정
#os.environ['HADOOP_HOME']=os.getcwd() # 현재 디렉터리를 HADOOP_HOME으로 설정
#os.environ["PATH"] += os.path.join(os.environ['HADOOP_HOME'], 'bin') # PATH에 Hadoop 바이너리 추가

In [6]:
#하둡 설치 --> 입출력을 할 때 하둡 엄청 중요
#file util 할 때 winutils.exe --> 파일 입출력을 맞추는 역할

In [7]:
myConf=pyspark.SparkConf() # 기본 설정 객체 생성, 여기에 필요한 설정 정의
#myConf=pyspark.SparkConf().set("spark.driver.bindAddress", "127.0.0.1") 드라이버 바인딩 주소 설정
#myConf=pyspark.SparkConf().set("spark.jars.packages", "org.mongodb.spark:mongo-spark-connector_2.13:10.1.1")

In [8]:
#pyspark --conf spark.python.profile.memory=true

In [ ]:
spark = pyspark.sql.SparkSession\
    .builder\
    .master("local")\
    .appName("myApp")\
    .config(conf=myConf)\
    .getOrCreate()

In [ ]:
#spark변수를 기본으로 띄워 두어야 한다

#관행적으로 spark = 으로 정의한다
#.연산자로 계속 이어진다! \는 계속 명령어가 . 으로 체이닝 되고 있음 
#다만 줄바꿈이 있으면 오류가 발생하는 경우가 많아서 줄바꿈X\이걸 꼭 넣어야해
#master: 쓰는 방식!
#appname: 이름 정해주는 거
#config: 위에 만든 거 그대로
#get...:메모리에 있으면 그거 쓰고 없으면 만들기!
spark = pyspark.sql.SparkSession\
    .builder\
    .master("local")\
    .appName("myApp")\
    .config(conf=myConf)\
    .getOrCreate()

In [ ]:
import os, sys
import pyspark

spark.version

In [ ]:
import sys
sys.version

In [ ]:
myList=[1,2,3,4,5,6,7]

In [ ]:
myRdd1 = spark.sparkContext.parallelize(myList)

In [ ]:
myRdd1.take(3) #Py4JJavaError가 나면 PSPARK_PYTHON, PYSPARK_DRIVER_PYTHON 경로 설정해야 한다.

In [ ]:
!java --version

In [ ]:
#java 에는 오라클이 jdk를 제공하는데 이거 말고 openjdk로 설치하기 기능은 동일함